### ISSUE TITLE
Pequeño problema ejecutando el script desde Windows

### ISSUE THREAD

**Issue by neofito** [sch3m4/androidpatternlock#2]
En primer lugar darte la enhorabuena por la herramienta ;)

Si lanzas el script desde un Windows utilizando cmd.exe al finalizar el proceso muestra el patrón, pero dado que los códigos de color no se interpretan el resultado es algo críptico.

Realmente no es un gran problema pero creo que estaría bien detectar el sistema en el que te encuentras o, directamente, prescindir de los códigos de colores al mostrar el resultado.

**Comment by sch3m4** [comment]
Corregido, gracias Neofito! =)
