### ISSUE TITLE
'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by linghu258** [sch3m4/androidpatternlock#6]
The line: gest = f.read(hashlib.sha1().digest_size).encode('hex')
is causing an error "bytes object has no attribute encode" when I ran the python script with the sample key. 

Please assist. Thanks

**Comment by linghu258** [comment]
The error has been solved, code has been updated.

**Comment by Dhrhciebcy** [comment]
Are you shure about that? He still gives me that error. Could it be a Python version problem?
